[package]
name = "rtz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.72", features = ["backtrace"] }
tokio = { version = "1.29.1", features = ["full"] }
rayon = "1.7.0"
geojson = "0.24.1"
geo = "0.26.0"
chashmap = "2.2.2"
async-trait = "0.1.71"

rand = "0.8.5"
cached = "0.44.0"

serde = { version = "1.0.126" }
serde_json = "1.0.64"

tinyvec = "1.6.0"

[dev-dependencies]
pretty_assertions = "1.4.0"