[package]
name = "rtz"
version = "0.3.2"
edition = "2021"
authors = ["Aaron Roney <twitchax@gmail.com>"]
license = "MIT"
description = "A tool to easily work with time zones via a binary, a library, or a server."
readme = "README.md"
homepage = "https://github.com/twitchax/rtz"
repository = "https://github.com/twitchax/rtz"
keywords = ["cli", "time", "zone", "timezone"]
categories = ["command-line-utilities"]

[lib]
name = "rtzlib"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "rtz"
path = "src/bin.rs"
required-features = ["cli"]

[features]
default = ["cli"]

cli = ["clap"]
web = ["tokio", "rocket", "rocket_okapi", "rocket_cors", "config", "log", "simple_logger", "schemars", "chrono"]
wasm = ["wasm-bindgen", "wasm-bindgen-futures", "wee_alloc", "js-sys"]

[dependencies]
anyhow = { version = "1.0.72", features = ["backtrace"] }
rayon = "1.7.0"
geojson = "0.24.1"
geo = "0.26.0"
chashmap = "2.2.2"
async-trait = "0.1.71"

rand = "0.8.5"
getrandom = { version = "0.2", features = ["js"] }

cached = "0.44.0"

serde = { version = "1.0.126" }
serde_json = "1.0.64"

bincode = { version = "2.0.0-rc.3", git = "https://github.com/bincode-org/bincode.git", default-features = false, features = ["alloc", "serde"] }

# cli
clap = { version = "4.0.29", features = ["derive"], optional = true }

# web
tokio = { version = "1.29.1", features = ["rt"], optional = true }
rocket = { version = "0.5.0-rc.3", features = ["secrets", "tls", "json"], optional = true }
rocket_okapi = { version = "0.8.0-rc.3", features = ["swagger", "rapidoc"], optional = true }
rocket_cors = { version = "0.6.0-alpha2", optional = true }
config = { version = "0.13.3", optional = true }
log = { version = "0.4.8", features = ["release_max_level_info"], optional = true }
simple_logger = { version = "4.2.0", optional = true }
schemars = { version = "0.8.6", features = ["chrono"], optional = true }
chrono = { version = "0.4.19", features = ["serde"], optional = true }

# wasm
wasm-bindgen = { version = "0.2.84", optional = true }
wasm-bindgen-futures = { version = "0.4.34", optional = true }
wee_alloc = { version = "0.4.5", optional = true }
js-sys = { version = "0.3.61", optional = true }

[dev-dependencies]
pretty_assertions = "1.4.0"