[package]
name = "rtz"
version = "0.1.0"
edition = "2021"
authors = ["Aaron Roney <twitchax@gmail.com>"]
license = "MIT"
description = "A tool to easily work with time zones via a binary, a library, or a server."
readme = "README.md"
homepage = "https://github.com/twitchax/rtz"
repository = "https://github.com/twitchax/rtz"
keywords = ["cli", "time", "zone", "timezone"]
categories = ["command-line-utilities"]

[lib]
name = "rtzlib"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "rtz"
path = "src/bin.rs"
required-features = ["cli"]

[features]
default = ["cli"]

cli = ["clap"]

[dependencies]
anyhow = { version = "1.0.72", features = ["backtrace"] }
tokio = { version = "1.29.1", features = ["full"] }
rayon = "1.7.0"
geojson = "0.24.1"
geo = "0.26.0"
chashmap = "2.2.2"
async-trait = "0.1.71"

rand = "0.8.5"
cached = "0.44.0"

serde = { version = "1.0.126" }
serde_json = "1.0.64"

bincode = { version = "2.0.0-rc.3", git = "https://github.com/bincode-org/bincode.git", default-features = false, features = ["alloc", "serde"] }

# cli
clap = { version = "4.0.29", features = ["derive"], optional = true }

[dev-dependencies]
pretty_assertions = "1.4.0"