[workspace]
members = ["rtz-core", "rtz"]

[profile.dev.build-override]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false

[profile.test.build-override]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false

[profile.release.build-override]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false