[package]
name = "rtz-build"
version = "0.2.4"
edition = "2021"
authors = ["Aaron Roney <twitchax@gmail.com>"]
license = "MIT"
description = "The build crate for `rtz`."
readme = "../README.md"
homepage = "https://github.com/twitchax/rtz"
repository = "https://github.com/twitchax/rtz"
keywords = ["cli", "time", "zone", "timezone"]
categories = ["command-line-utilities"]

[features]
default = []
full = ["tz-ned", "self-contained"]

force-rebuild = []
self-contained = ["reqwest", "zip"]
tz-ned = []
tz-osm = []

[dependencies]
rtz-core = { path = "../rtz-core", version = "0.1.0" }

# self-contained
[target.'cfg(not(target_family = "wasm"))'.dependencies]
reqwest = { version = "0.11.18", optional = true, features = ["blocking"] }
zip = { version = "0.6.6", optional = true }